name: Build and push develop docker image to GCR

on:
  push:
    tags:
    - dev**
    - test**
    - pre-release**

jobs:

  build-platform-image:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t
